a=list(range(10))

print(a)
print(a[2])
print(a[2:])
print(a[:2])
print(a[2:6])
print(a[2:-2])
print(a[-6:-2])
print(a[:])
print(a[2::2])
print(a[:6:2])
print(a[2:6:2])
print(a[::-1])
print(a[::-2])
print(a[-6:-2:1])